server:
  port: 8095

spring:
  application:
    name: financial-identity-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_identity_service_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  redis:
    data:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/identity-platform

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      enabled: true

logging:
  level:
    com.identity.platform: DEBUG
    org.springframework.security: DEBUG
