server:
  port: 8085

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888  # URL du config-service
  cloud:
    config:
      enabled: true
      fail-fast: false