server:
  port: 8093

spring:
  application:
    name: family-identity-service
  config:
    import: optional:configserver:http://localhost:8888  # URL du config-service
  cloud:
    config:
      enabled: true
      fail-fast: false